version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"

  backend:
    build: ./swi-backend
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
